# Generated by Django 6.0.5 on 2026-05-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodexInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.IntegerField()),
                ("thread_id", models.CharField(db_index=True, max_length=128)),
                ("cwd", models.CharField(max_length=4096)),
                ("prompt", models.TextField(blank=True, default="")),
                ("events_path", models.CharField(max_length=4096)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("starting", "starting"),
                            ("running", "running"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default="starting",
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["thread_id", "-started_at"],
                        name="main_codexi_thread__6aae4e_idx",
                    ),
                    models.Index(
                        fields=["status"], name="main_codexi_status_da9bcd_idx"
                    ),
                ],
            },
        ),
    ]
