# Generated by Django 6.0.5 on 2026-05-15 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=128)),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "pending"),
                            ("approved", "approved"),
                            ("denied", "denied"),
                            ("abort", "abort"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="main.codexinstance",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["instance", "-created_at"],
                        name="main_approv_instanc_d98806_idx",
                    )
                ],
            },
        ),
    ]
