# Generated by Django 6.0.5 on 2026-05-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_approvalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="codexinstance",
            name="interrupt_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
