# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_codexinstance_interrupt_requested_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="codexinstance",
            name="developer_instructions",
            field=models.TextField(blank=True, default=""),
        ),
    ]
