# Generated by Codex on 2026-05-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_codexinstance_developer_instructions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(blank=True, default="", max_length=256)),
                (
                    "reasoning_effort",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "sandbox_policy",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "approval_mode",
                    models.CharField(
                        blank=True, default="auto_review", max_length=32
                    ),
                ),
                ("extra_system_prompt", models.TextField(blank=True, default="")),
                ("show_archived_sessions", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hitch_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
