# Generated by Django 6.0 on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="use_worktrees",
            field=models.BooleanField(default=False),
        ),
    ]
