# Generated by Django 6.0.5 on 2026-05-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_merge_0026_project_scoped_proposed_sessions_0026_standingordermemory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='proposedsession',
            new_name='main_propos_project_628165_idx',
            old_name='main_propos_project_6fd310_idx',
        ),
    ]
