# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_qa_panel_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='standingorder',
            name='autonomy',
            field=models.CharField(
                choices=[
                    ('propose_only', 'Propose only'),
                    ('draft_patch', 'Draft patch'),
                    ('draft_pr', 'Draft PR'),
                ],
                default='propose_only',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='proposedsession',
            name='outcome_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
