# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_standingorder_autonomy_proposedsession_outcome_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="spec_critic_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
