# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_web_search_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="standingorder",
            name="auto_qa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionmetadata",
            name="auto_qa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="codexinstance",
            name="auto_qa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="codexinstance",
            name="auto_qa_triggered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="auto_qa_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
