# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_web_search_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="standingorder",
            name="auto_proposal_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="auto_proposal_last_no_proposal_sha",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
