# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_standingorder_auto_proposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="codexinstance",
            name="auto_merge_to_local_branch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="codexinstance",
            name="auto_merge_branch",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="sessionmetadata",
            name="auto_merge_to_local_branch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionmetadata",
            name="auto_merge_branch",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="auto_merge_to_local_branch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="standingorder",
            name="auto_merge_branch",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
