# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_standingorder_auto_proposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="codexinstance",
            name="input_image_paths",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="codexinstance",
            name="input_attachment_paths",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="codexinstance",
            name="input_attachment_cleanup_requested",
            field=models.BooleanField(default=False),
        ),
    ]
