# Generated by Codex for session usage cache improvements.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_codexinstance_input_image_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedsessiontokenusage",
            name="daily_usage",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
