# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_auto_merge_local_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionmetadata",
            name="codex_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="sessionmetadata",
            name="codex_created_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionmetadata",
            name="codex_display_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sessionmetadata",
            name="codex_last_synced_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionmetadata",
            name="codex_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sessionmetadata",
            name="codex_path",
            field=models.CharField(blank=True, default="", max_length=4096),
        ),
        migrations.AddField(
            model_name="sessionmetadata",
            name="codex_thread_source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="sessionmetadata",
            name="codex_preview",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sessionmetadata",
            name="codex_updated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="sessionmetadata",
            index=models.Index(
                fields=["project", "codex_archived", "-codex_updated_at"],
                name="main_sessio_project_18730c_idx",
            ),
        ),
    ]
