# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_sessionmetadata_codex_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionIndexSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=32, unique=True)),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "next_cursor",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
