# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_sessionindexsyncstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionmetadata",
            name="usage_last_checked_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
