# Generated by Codex on 2026-05-24

from django.db import migrations, models


STANDING_ORDER_AGENT_PROMPT_TITLE = "You are Hitch's standing order agent."
STANDING_ORDER_JUDGE_PROMPT_TITLE = (
    "You are Hitch's standing order confidence judge."
)


def _update_thread_ids(queryset, thread_ids: set[str]) -> None:
    ids = [thread_id for thread_id in thread_ids if thread_id]
    for index in range(0, len(ids), 500):
        queryset.filter(thread_id__in=ids[index : index + 500]).update(
            is_hidden_system_session=True
        )


def backfill_hidden_system_sessions(apps, schema_editor) -> None:
    SessionMetadata = apps.get_model("main", "SessionMetadata")
    CodexInstance = apps.get_model("main", "CodexInstance")
    SystemAgentRun = apps.get_model("main", "SystemAgentRun")

    SessionMetadata.objects.filter(codex_thread_source="subagent").update(
        is_hidden_system_session=True
    )
    SessionMetadata.objects.filter(
        codex_name=STANDING_ORDER_AGENT_PROMPT_TITLE,
        codex_preview__startswith=f"{STANDING_ORDER_AGENT_PROMPT_TITLE}\n\n",
        codex_preview__contains="Standing order title:",
    ).filter(codex_preview__contains="Standing order goal:").filter(
        codex_preview__contains="Return only JSON matching this shape:"
    ).update(
        is_hidden_system_session=True
    )
    SessionMetadata.objects.filter(
        codex_name=STANDING_ORDER_JUDGE_PROMPT_TITLE,
        codex_preview__startswith=f"{STANDING_ORDER_JUDGE_PROMPT_TITLE}\n\n",
        codex_preview__contains="Standing order title:",
    ).filter(codex_preview__contains="Candidate session JSON:").filter(
        codex_preview__contains="Return only JSON matching this shape:"
    ).update(
        is_hidden_system_session=True
    )

    hidden_thread_ids = set(
        SystemAgentRun.objects.exclude(thread_id="")
        .exclude(agent_kind="demo")
        .values_list("thread_id", flat=True)
    )
    hidden_thread_ids.update(
        CodexInstance.objects.filter(purpose="system_agent")
        .exclude(thread_id="")
        .exclude(agent_kind="demo")
        .values_list("thread_id", flat=True)
    )
    _update_thread_ids(SessionMetadata.objects, hidden_thread_ids)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_sessionmetadata_usage_last_checked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionmetadata",
            name="is_hidden_system_session",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(backfill_hidden_system_sessions, migrations.RunPython.noop),
    ]
