# Generated by Django 6.0.5 on 2026-05-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0048_reset_stale_stage_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedsessiontokenusage",
            name="usage_logic_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
