# Generated by Django 6.0.5 on 2026-05-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0049_archivedsessiontokenusage_usage_logic_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionmetadata",
            name="pr_url",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
