# Generated by Django 6.0.5 on 2026-05-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0050_sessionmetadata_pr_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemworkflow",
            name="pr_monitor_next_poll_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
