# Generated by Django 6.0.5 on 2026-06-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0052_sessionmetadata_stage_pr_refresh"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("attempted_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
