# Generated by Django 6.0.5 on 2026-06-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0051_autonomousgoal_deleted_at"),
        ("main", "0052_autonomousgoal_provider"),
    ]

    operations = []
