# Generated by Django 6.0.5 on 2026-06-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0052_sessionmetadata_stage_pr_refresh"),
        ("main", "0053_merge_20260602_1656"),
    ]

    operations = []
