# Generated by Django 6.0.5 on 2026-06-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0053_refreshthrottle"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sessionmetadata",
            name="main_sessio_project_0daead_idx",
        ),
        migrations.AddIndex(
            model_name="sessionmetadata",
            index=models.Index(
                fields=["-codex_updated_at", "-id"],
                name="main_sessio_codex_updated_idx",
            ),
        ),
    ]
