# Generated by Django 6.0.5 on 2026-06-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_project_auto_pull_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemworkflow',
            name='status',
            field=models.CharField(choices=[('running', 'running'), ('queued', 'queued'), ('blocked', 'blocked'), ('completed', 'completed'), ('failed', 'failed'), ('max_iterations_reached', 'max iterations reached')], default='running', max_length=64),
        ),
    ]
