# Generated by Django 6.0.5 on 2026-05-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0062_project_auto_pull_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="codexinstance",
            name="backend",
            field=models.CharField(
                choices=[("codex", "Codex"), ("claude", "Claude Code")],
                default="codex",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="codexinstance",
            name="claude_session_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
