# Generated by Django 6.0.5 on 2026-05-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0063_codexinstance_backend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="provider",
            field=models.CharField(blank=True, default="codex", max_length=16),
        ),
    ]
