# Generated by Django 6.0.5 on 2026-05-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0064_usersettings_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="autonomousgoal",
            name="provider",
            field=models.CharField(
                choices=[("codex", "Codex"), ("claude", "Claude Code")],
                default="codex",
                max_length=16,
            ),
        ),
    ]
