# Generated by Django 6.0.5 on 2026-09-10 14:50

import os
import re
import subprocess
from datetime import timedelta
from pathlib import Path

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


_RETIRED_ERROR = "Autonomous goals removed during upgrade"


def retire_autonomous_goals(apps, schema_editor):
    database = schema_editor.connection.alias
    Proposal = apps.get_model("main", "ProposedSession")
    Workflow = apps.get_model("main", "SystemWorkflow")
    Run = apps.get_model("main", "SystemAgentRun")
    Instance = apps.get_model("main", "CodexInstance")
    Approval = apps.get_model("main", "ApprovalRequest")
    UserInput = apps.get_model("main", "UserInputRequest")
    now = timezone.now()

    # Keep source history and accepted sessions after removing goal relations.
    for proposal in Proposal.objects.using(database).filter(autonomous_goal__isnull=False).iterator():
        updates = {}
        if proposal.project_id is None:
            updates["project_id"] = proposal.autonomous_goal.project_id
        if proposal.source_session_id is None:
            updates["source_session_id"] = proposal.candidate_session_id
        if proposal.outcome_status == "" or (
            proposal.outcome_status == "accepted" and proposal.accepted_session_id is None
        ):
            updates.update(
                outcome_status="dismissed",
                outcome_notes=_RETIRED_ERROR,
                updated_at=now,
            )
        if updates:
            Proposal.objects.using(database).filter(pk=proposal.pk).update(**updates)

    workflows = Workflow.objects.using(database).filter(kind="autonomous_goal_run")
    # Backdate retirement so the first reconciliation sweep skips terminal grace.
    instances = Instance.objects.using(database).filter(
        models.Q(workflow_id__in=workflows.values("pk"))
        | models.Q(agent_kind__in=("autonomous_goal_run", "autonomous_goal_reviewer")),
        purpose="system_agent",
        status__in=("starting", "running"),
    )
    instance_ids = list(instances.values_list("pk", flat=True))
    instances.update(
        status="failed",
        ended_at=now - timedelta(days=1),
        interrupt_requested_at=now,
        workflow_routing_started_at=now,
        error=_RETIRED_ERROR,
    )
    Approval.objects.using(database).filter(instance_id__in=instance_ids, decision="").update(
        decision="cancel",
        decided_at=now,
    )
    UserInput.objects.using(database).filter(instance_id__in=instance_ids, response__isnull=True).update(
        response={"answers": {}},
        responded_at=now,
    )
    Run.objects.using(database).filter(
        workflow_id__in=workflows.values("pk"),
        status__in=("starting", "running"),
    ).update(status="failed", error=_RETIRED_ERROR, updated_at=now)
    workflows.filter(status__in=("running", "blocked")).update(
        status="completed",
        step="retired",
        updated_at=now,
    )


def release_goal_snapshot_refs(apps, schema_editor):
    Project = apps.get_model("main", "Project")
    # Freeze cleanup in the migration; runtime goal snapshot helpers are removed.
    owned_ref = re.compile(r"refs/hitch/autonomous-goals/[1-9][0-9]*/[0-9a-f]{32}")
    environment = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    environment["GIT_TERMINAL_PROMPT"] = "0"
    environment["LC_ALL"] = "C"
    projects = Project.objects.using(schema_editor.connection.alias).filter(autonomous_goals__isnull=False).distinct()
    for repo_path in projects.values_list("repo_path", flat=True):
        if not Path(repo_path).is_dir():
            continue
        command = ["git", "-c", "core.hooksPath=/dev/null", "-C", repo_path]
        refs = subprocess.run(
            [*command, "for-each-ref", "--format=%(refname)", "refs/hitch/autonomous-goals/"],
            env=environment,
            text=True,
            capture_output=True,
            check=False,
            timeout=10,
        )
        # Stale projects can outlive their Git metadata. Other Git failures must
        # remain visible so a retry can still release their owned refs.
        if refs.returncode and refs.stderr.startswith("fatal: not a git repository"):
            continue
        refs.check_returncode()
        deletes = "".join(f"delete {ref}\n" for ref in refs.stdout.splitlines() if owned_ref.fullmatch(ref))
        if deletes:
            subprocess.run(
                [*command, "update-ref", "--stdin"],
                input=deletes,
                env=environment,
                text=True,
                capture_output=True,
                check=True,
                timeout=10,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0079_recentprompt_project"),
    ]

    operations = [
        migrations.RunPython(retire_autonomous_goals, migrations.RunPython.noop),
        migrations.RunPython(release_goal_snapshot_refs, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="autonomousgoal",
            name="main_autono_project_9a398c_idx",
        ),
        migrations.RemoveIndex(
            model_name="proposedsession",
            name="main_propos_autonom_c5613b_idx",
        ),
        migrations.AlterField(
            model_name="proposedsession",
            name="accepted_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_proposals",
                to="main.sessionmetadata",
            ),
        ),
        migrations.RemoveField(
            model_name="proposedsession",
            name="autonomous_goal",
        ),
        migrations.RemoveField(
            model_name="proposedsession",
            name="candidate_session",
        ),
        migrations.RemoveField(
            model_name="proposedsession",
            name="judge_session",
        ),
        migrations.RemoveField(
            model_name="proposedsession",
            name="source_workflow",
        ),
        migrations.DeleteModel(
            name="AutonomousGoal",
        ),
    ]
