# Generated by Django 6.0.5 on 2026-09-28 23:05

from django.db import migrations
from django.utils import timezone


def archive_retired_sessions(apps, schema_editor):
    database = schema_editor.connection.alias
    Metadata = apps.get_model("main", "SessionMetadata")
    Instance = apps.get_model("main", "CodexInstance")
    Run = apps.get_model("main", "SystemAgentRun")
    Proposal = apps.get_model("main", "ProposedSession")
    now = timezone.now()
    accepted = set(
        Proposal.objects.using(database)
        .filter(
            outcome_status="accepted",
            accepted_session__isnull=False,
        )
        .values_list("accepted_session__thread_id", flat=True)
    )
    # Native Codex subagents have their own picker and are not retired workers.
    retired = set(
        Metadata.objects.using(database)
        .filter(
            is_hidden_system_session=True,
        )
        .exclude(codex_thread_source="subagent")
        .values_list("thread_id", flat=True)
    )
    retired.update(Run.objects.using(database).values_list("thread_id", flat=True))
    workers = Instance.objects.using(database).filter(purpose="system_agent")
    retired.update(workers.values_list("thread_id", flat=True))
    retired.difference_update(accepted | {""})
    # An archive override survives stale Codex state and complete index sweeps.
    for thread_id in sorted(retired):
        worker = workers.filter(thread_id=thread_id).order_by("-pk").first()
        metadata, _ = Metadata.objects.using(database).get_or_create(
            thread_id=thread_id,
            defaults={
                "cwd": worker.cwd if worker else "",
                "codex_display_title": (worker.display_author or worker.agent_kind or thread_id)
                if worker
                else thread_id,
                "codex_created_at": worker.started_at if worker else now,
                "codex_updated_at": (worker.ended_at or worker.started_at) if worker else now,
            },
        )
        Metadata.objects.using(database).filter(thread_id=thread_id).update(
            codex_archived=True,
            archive_local_only=True,
            codex_archived_at=metadata.codex_archived_at or now,
            codex_updated_at=metadata.codex_updated_at or now,
        )
    Proposal.objects.using(database).filter(inbox_kind="notice").delete()
    Instance.objects.using(database).filter(purpose__in=("system_agent", "system_feedback")).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0085_remove_auto_qa"),
    ]

    operations = [
        migrations.RunPython(archive_retired_sessions, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="systemagentrun",
            name="main_system_workflo_62f332_idx",
        ),
        migrations.RemoveIndex(
            model_name="systemagentrun",
            name="main_system_agent_k_fa0e6b_idx",
        ),
        migrations.RemoveConstraint(
            model_name="systemagentrun",
            name="uniq_system_agent_run_instance",
        ),
        migrations.RemoveIndex(
            model_name="systemworkflow",
            name="main_system_kind_f8ef00_idx",
        ),
        migrations.RemoveConstraint(
            model_name="systemworkflow",
            name="uniq_running_system_workflow",
        ),
        migrations.RemoveIndex(
            model_name="codexinstance",
            name="main_codexi_purpose_e781e3_idx",
        ),
        migrations.RemoveField(
            model_name="proposedsession",
            name="inbox_kind",
        ),
        migrations.RemoveField(
            model_name="sessionmetadata",
            name="is_hidden_system_session",
        ),
        migrations.RemoveField(
            model_name="codexinstance",
            name="display_author",
        ),
        migrations.RemoveField(
            model_name="codexinstance",
            name="purpose",
        ),
        migrations.RemoveField(
            model_name="codexinstance",
            name="workflow_id",
        ),
        migrations.DeleteModel(
            name="SystemAgentRun",
        ),
        migrations.DeleteModel(
            name="SystemWorkflow",
        ),
    ]
